name: deploy-vault.ci

on:
  pull_request:

permissions:
  checks: write
  contents: write

env:
  DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

jobs:
  deploy-vault:
    name: Deploys missing infrared vaults
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }} # added to ensure that new workflows are triggered when CI fixes things. See https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
    
      - name: Deploy vault
        run: pnpm deploy-vault

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "feat: add addresses of deployed vaults"
          commit_options: '--no-verify'
